debug: true

checkers:
  webhost:
    popular:
      - name: Yandex
        filter: host("ya.ru")
      - name: Google
        filter: host("www.google.com")
      - name: YouTube
        filter: host("www.youtube.com")
      - name: Instagram
        filter: host("www.instagram.com")
    infra:
      - name: Cloudflare
        filter: org("cloudflare")
      - name: Akamai
        filter: org("akamai")
      - name: Fastly
        filter: org("fastly")
      - name: Oracle
        filter: org("oracle")
      - name: DigitalOcean
        filter: org("digitalocean")
        count: 2
      - name: Hetzner DE
        filter: org("hetzner") && country("de")
        count: 2
      - name: Hetzner FI
        filter: org("hetzner") && country("fi")
        count: 2
      - name: OVH
        filter: as(16276)
        count: 2
      - name: Gcore
        filter: as(199524)
    workers: 8
    tcp-conn-timeout: 3s
    tls-handshake-timeout: 3s
    tcp-read-timeout: 15s
    tcp-write-timeout: 15s
    tcp-write-buf: 4096
    tcp-read-buf: 4096
    tcp1620-n-bytes: 65536
    key-log-path: "/tmp/keys.log"
    http-static-headers:
      Accept: "*/*"
      Content-Type: application/octet-stream
      User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36

  cidrwhitelist:
    timeout: 15s
    whitelisted:
      - https://max.ru/
      - https://ya.ru/
      - https://vk.ru/
    regular:
      - https://github.com/
      - https://ru.wikipedia.org/
      - https://www.google.com/

  whoami:
      timeout: 30s

subnetfilter:
  workers: 8

webhostfarm:
  workers: 8
  tcp-conn-timeout: 3s
  tls-handshake-timeout: 3s

inetlookup:
  ripe-api-url: https://stat.ripe.net/data/
  yandex-api-url: https://yandex.ru/internet/api/v0/

httputil:
  browser-headers:
    Accept-Language: ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7
    User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/133.0.0.0 Safari/537.36
